<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ostad_Helper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Views\Shared\_Layout.cshtml.Bak2" />
    <Content Include="Views\Shared\_Layout.cshtml.hat" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Utils\CacheHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.11.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.11.0" />
  </ItemGroup>

</Project>
